<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Sample application — CQRS commands/queries for the product catalog.</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AcmeApp.Api.Domain\AcmeApp.Api.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\Content\YourApp.Domain\YourApp.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\Content\YourApp.Application\YourApp.Application.csproj" />
  </ItemGroup>

</Project>